version: "20.10"

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: microservicio-agreement-db
    networks:
      - network3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: user
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27019:27017"
    env_file:
      - .env

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    container_name: microservicio-agreement-db-api
    networks:
      - network3
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8084:8081" # Puerto del host:Puerto del contenedor
    env_file:
      - .env
networks:
  network3:
