# Use root/example as user/password credentials
version: "3.1"

services:
  golang-auth-api:
    image: ${DOCKER_REGISTRY-}microservicio-agreement-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9094:4000
    networks:
      - network3
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      JWTSecret: ${JWTSecret}
      JWTExpirationMs: ${JWTExpirationMs}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

networks:
  network3:
