# Use root/example as user/password credentials
version: "3.1"

services:
  golang-agreement-api:
    image: ${DOCKER_REGISTRY-}microservicio-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9092:4000
    volumes:
      - ./uploads:/uploads
      - ./files:/files
    networks:
      - network3
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      JWTSecret: ${JWTSecret}
    env_file:
      - .env

networks:
  network3:

#docker build -t almendraivan/microservice-agreement:v0 .
#docker run  -p 9092:4000 --name codigo-go-agreement almendraivan/microservice-agreement:v0