# Use root/example as user/password credentials
version: "3.1"

services:
  golang-media-api:
    image: ${DOCKER_REGISTRY-}microservicio-media-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:4000
    volumes:
      - ./uploads:/uploads
      - ./files:/files
    networks:
      - network1
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      JWTSecret: ${JWTSecret}

networks:
  network1:
